yarnPath: .yarn/releases/yarn-3.2.1.cjs
nodeLinker: node-modules

npmScopes:
  'owner':
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com/'
    npmAuthToken: 'your github PAT'
